export type Question = {
  id: string;
  question: string;
  question_type: 'text' | 'image' | 'video';
  category: string;
  value: number;
  alternatives: string[];
  correct: string;
  state: QuestionState
  image?:string
}

export type QuestionState = 'unasked' | 'right' | 'wrong';

export type QuestionCategory = {
  name: string;
  questions: Question[];
  isChosen: boolean;
}

export const allQuestionCategories: QuestionCategory[] = [
  {
    name: 'General Knowledge',
    questions: [
      {
        id: 'gk-1',
        question: 'What is the capital of France?',
        question_type: 'text',
        category: 'General Knowledge',
        value: 100,
        alternatives: ['Paris', 'Rome', 'Berlin', 'Madrid'],
        correct: 'Paris',
        state: 'unasked',
      },
      {
        id: 'gk-2',
        question: 'How many continents are there on Earth?',
        question_type: 'text',
        category: 'General Knowledge',
        value: 200,
        alternatives: ['5', '6', '7', '8'],
        correct: '7',
        state: 'unasked',
      },
      {
        id: 'gk-3',
        question: 'What gas do plants absorb from the atmosphere?',
        question_type: 'text',
        category: 'General Knowledge',
        value: 300,
        alternatives: ['Oxygen', 'Carbon Dioxide', 'Nitrogen', 'Hydrogen'],
        correct: 'Carbon Dioxide',
        state: 'unasked',
      },
      {
        id: 'gk-4',
        question: 'Which ocean is the largest?',
        question_type: 'text',
        category: 'General Knowledge',
        value: 400,
        alternatives: ['Atlantic', 'Indian', 'Pacific', 'Arctic'],
        correct: 'Pacific',
        state: 'unasked',
      },
      {
        id: 'gk-5',
        question: 'What is the boiling point of water at sea level (°C)?',
        question_type: 'text',
        category: 'General Knowledge',
        value: 500,
        alternatives: ['90', '95', '100', '110'],
        correct: '100',
        state: 'unasked',
      },
    ],
    isChosen: false,
  },
  {
    name: 'TV shows',
    questions: [
      {
        id: 'mtv-1',
        question: 'Who played Iron Man in the Marvel movies?',
        question_type: 'text',
        category: 'Movies & TV',
        value: 100,
        alternatives: [
          'Chris Evans',
          'Robert Downey Jr.',
          'Chris Hemsworth',
          'Mark Ruffalo',
        ],
        correct: 'Robert Downey Jr.',
        state: 'unasked',
      },
      {
        id: 'mtv-2',
        question: 'Which TV show is set in the fictional town of Hawkins?',
        question_type: 'text',
        category: 'Movies & TV',
        value: 200,
        alternatives: [
          'Dark',
          'Stranger Things',
          'The X-Files',
          'Riverdale',
        ],
        correct: 'Stranger Things',
        state: 'unasked',
      },
      {
        id: 'mtv-3',
        question: 'Which movie features the quote “I’ll be back”?',
        question_type: 'text',
        category: 'Movies & TV',
        value: 300,
        alternatives: [
          'Rocky',
          'Die Hard',
          'The Terminator',
          'Predator',
        ],
        correct: 'The Terminator',
        state: 'unasked',
      },
      {
        id: 'mtv-4',
        question: 'What animated movie features a clownfish named Nemo?',
        question_type: 'text',
        category: 'Movies & TV',
        value: 400,
        alternatives: [
          'Shark Tale',
          'Finding Nemo',
          'The Little Mermaid',
          'Moana',
        ],
        correct: 'Finding Nemo',
        state: 'unasked',
      },
      {
        id: 'mtv-5',
        question: 'Which streaming service produced the series “The Crown”?',
        question_type: 'text',
        category: 'Movies & TV',
        value: 500,
        alternatives: ['Hulu', 'Netflix', 'Amazon Prime', 'HBO'],
        correct: 'Netflix',
        state: 'unasked',
      },
    ],
    isChosen: false,
  },
  {
    name: 'Oscars',
    questions: [
      {
        id: 'os-1',
        question: 'Which movie won the first ever Academy Award for Best Picture?',
        question_type: 'text',
        category: 'Oscars',
        value: 100,
        alternatives: ['Wings', 'Sunrise', 'Metropolis', 'The Jazz Singer'],
        correct: 'Wings',
        state: 'unasked',
      },
      {
        id: 'os-2',
        question: 'Who has won the most Academy Awards for Best Actress?',
        question_type: 'text',
        category: 'Oscars',
        value: 200,
        alternatives: ['Meryl Streep', 'Katharine Hepburn', 'Frances McDormand', 'Bette Davis'],
        correct: 'Katharine Hepburn',
        state: 'unasked',
      },
      {
        id: 'os-3',
        question: 'In 2020, which film became the first non-English language movie to win Best Picture?',
        question_type: 'text',
        category: 'Oscars',
        value: 300,
        alternatives: ['Roma', 'Life is Beautiful', 'Parasite', 'Amour'],
        correct: 'Parasite',
        state: 'unasked',
      },
      {
        id: 'os-4',
        question: 'Which of these films holds the record for the most Oscar nominations (14) without a single win?',
        question_type: 'text',
        category: 'Oscars',
        value: 400,
        alternatives: ['The Color Purple', 'The Turning Point', 'La La Land', 'All About Eve'],
        correct: 'The Turning Point',
        state: 'unasked',
      },
      {
        id: 'os-5',
        question: 'Fernanda Montenegro, mother of Fernanda Torres became the first Brazilian and first Latin American to be nominated for the Academy Award for Best Actress. With what movie was that?',
        question_type: 'image',
        category: 'Oscars',
        value: 500,
        alternatives: ['Central do Brasil', 'Ainda estou aqui', 'Vitória', 'Senhora do destino'],
        correct: 'Tatum O’Neal',
        state: 'unasked',
      },
    ],
    isChosen: false,
  },
  {
  name: 'Pop Music',
  questions: [
    {
      id: 'pop-1',
      question: 'Which artist is known as the "King of Pop"?',
      question_type: 'text',
      category: 'Pop Music',
      value: 100,
      alternatives: ['Michael Jackson', 'Elvis Presley', 'Prince', 'Justin Timberlake'],
      correct: 'Michael Jackson',
      state: 'unasked',
    },
    {
      id: 'pop-2',
      question: 'Which pop group released the album "1989"?',
      question_type: 'text',
      category: 'Pop Music',
      value: 200,
      alternatives: ['One Direction', 'NSYNC', 'Backstreet Boys', 'Taylor Swift'],
      correct: 'Taylor Swift',
      state: 'unasked',
    },
    {
      id: 'pop-3',
      question: 'Which singer is famous for the hit song "Shape of You"?',
      question_type: 'text',
      category: 'Pop Music',
      value: 300,
      alternatives: ['Ed Sheeran', 'Bruno Mars', 'Shawn Mendes', 'Adele'],
      correct: 'Ed Sheeran',
      state: 'unasked',
    },
    {
      id: 'pop-4',
      question: 'Which pop icon performed at the Super Bowl halftime show in 2020?',
      question_type: 'text',
      category: 'Pop Music',
      value: 400,
      alternatives: ['Jennifer Lopez', 'Shakira', 'Beyoncé', 'Ariana Grande'],
      correct: 'Shakira',
      state: 'unasked',
    },
    {
      id: 'pop-5',
      question: 'What is the music of lady gaga',
      question_type: 'text',
      category: 'Pop Music',
      value: 500,
      alternatives: ['Abracadabra, Amor oo na na \n Abracadabra, Morta oo gaga \n Abracadabra Abra oo na na', '2008', '2009', '2010'],
      correct: '2008',
      state: 'unasked',
    },
  ],
  isChosen: false,
},
{
  name: 'Video Games',
  questions: [
    {
      id: 'vg-1',
      question: 'Which game features the character Mario?',
      question_type: 'text',
      category: 'Video Games',
      value: 100,
      alternatives: ['Sonic the Hedgehog', 'Mario Kart', 'The Legend of Zelda', 'Pac-Man'],
      correct: 'Mario Kart',
      state: 'unasked',
    },
    {
      id: 'vg-2',
      question: 'What is the best-selling video game of all time?',
      question_type: 'text',
      category: 'Video Games',
      value: 200,
      alternatives: ['Minecraft', 'Tetris', 'Grand Theft Auto V', 'Fortnite'],
      correct: 'Minecraft',
      state: 'unasked',
    },
    {
      id: 'vg-3',
      question: 'In which game do players compete in a battle royale on an island?',
      question_type: 'text',
      category: 'Video Games',
      value: 300,
      alternatives: ['Fortnite', 'Call of Duty', 'PUBG', 'Apex Legends'],
      correct: 'Fortnite',
      state: 'unasked',
    },
    {
      id: 'vg-4',
      question: 'Which video game series features the character Master Chief?',
      question_type: 'text',
      category: 'Video Games',
      value: 400,
      alternatives: ['Halo', 'Destiny', 'Gears of War', 'Mass Effect'],
      correct: 'Halo',
      state: 'unasked',
    },
    {
      id: 'vg-5',
      question: 'What is the name of the fictional world in "The Legend of Zelda"?',
      question_type: 'text',
      category: 'Video Games',
      value: 500,
      alternatives: ['Hyrule', 'Tamriel', 'Azeroth', 'Kanto'],
      correct: 'Hyrule',
      state: 'unasked',
    },
  ],
  isChosen: false,
},

  {
    name: 'Warhammer 40k',
    questions: [
      {
        id: 'wh-1',
        question: 'Who is the immortal ruler and god of the Imperium of Man?',
        question_type: 'text',
        category: 'Warhammer 40k',
        value: 100,
        alternatives: ['Horus Lupercal', 'The Emperor of Mankind', 'Roboute Guilliman', 'Malcador the Sigillite'],
        correct: 'The Emperor of Mankind',
        state: 'unasked',
      },
      {
        id: 'wh-2',
        question: 'Which Chaos God is known as the Blood God and the Lord of Skulls?',
        question_type: 'text',
        category: 'Warhammer 40k',
        value: 200,
        alternatives: ['Tzeentch', 'Nurgle', 'Slaanesh', 'Khorne'],
        correct: 'Khorne',
        state: 'unasked',
      },
      {
        id: 'wh-3',
        question: 'The Space Marine Chapter known as the "Blood Angels" suffers from which genetic flaw?',
        question_type: 'text',
        category: 'Warhammer 40k',
        value: 300,
        alternatives: ['The Black Rage', 'The Wulfen', 'The Flesh Change', 'The Red Thirst'],
        correct: 'The Black Rage',
        state: 'unasked',
      },
      {
        id: 'wh-4',
        question: 'What is the name of the mechanical, skeletal xenos race that seeks to reclaim their ancient empire?',
        question_type: 'text',
        category: 'Warhammer 40k',
        value: 400,
        alternatives: ['Aeldari', 'Tyranids', 'Necrons', 'T’au'],
        correct: 'Necrons',
        state: 'unasked',
      },
      {
        id: 'wh-5',
        question: 'During the Horus Heresy, which Primarch turned traitor and led the siege on Holy Terra?',
        question_type: 'text',
        category: 'Warhammer 40k',
        value: 500,
        alternatives: ['Leman Russ', 'Horus Lupercal', 'Sanguinius', 'Rogal Dorn'],
        correct: 'Horus Lupercal',
        state: 'unasked',
      },
    ],
    isChosen: false,
  },
  {
  name: 'Sports',
  questions: [
    {
      id: 'sp-1',
      question: 'In which sport would you use a "shuttlecock"?',
      question_type: 'text',
      category: 'Sports',
      value: 100,
      alternatives: ['Tennis', 'Badminton', 'Table Tennis', 'Squash'],
      correct: 'Badminton',
      state: 'unasked',
    },
    {
      id: 'sp-2',
      question: 'Which country has won the most FIFA World Cups?',
      question_type: 'text',
      category: 'Sports',
      value: 200,
      alternatives: ['Germany', 'Argentina', 'Brazil', 'Italy'],
      correct: 'Brazil',
      state: 'unasked',
    },
    {
      id: 'sp-3',
      question: 'What is the maximum score possible in a single game of ten-pin bowling?',
      question_type: 'text',
      category: 'Sports',
      value: 300,
      alternatives: ['200', '250', '300', '400'],
      correct: '300',
      state: 'unasked',
    },
    {
      id: 'sp-4',
      question: 'How many minutes is a standard professional rugby union match?',
      question_type: 'text',
      category: 'Sports',
      value: 400,
      alternatives: ['90 minutes', '80 minutes', '70 minutes', '60 minutes'],
      correct: '80 minutes',
      state: 'unasked',
    },
    {
      id: 'sp-5',
      question: 'Which golf tournament awards the winner a "Green Jacket"?',
      question_type: 'text',
      category: 'Sports',
      value: 500,
      alternatives: ['The U.S. Open', 'The Open Championship', 'PGA Championship', 'The Masters'],
      correct: 'The Masters',
      state: 'unasked',
    },
  ],
  isChosen: false,
},
{
  name: 'History',
  questions: [
    {
      id: 'hi-1',
      question: 'Who was the first President of the United States?',
      question_type: 'text',
      category: 'History',
      value: 100,
      alternatives: ['Thomas Jefferson', 'Abraham Lincoln', 'George Washington', 'John Adams'],
      correct: 'George Washington',
      state: 'unasked',
    },
    {
      id: 'hi-2',
      question: 'In which year did the Titanic sink?',
      question_type: 'text',
      category: 'History',
      value: 200,
      alternatives: ['1912', '1905', '1920', '1898'],
      correct: '1912',
      state: 'unasked',
    },
    {
      id: 'hi-3',
      question: 'The Renaissance period began in which European country?',
      question_type: 'text',
      category: 'History',
      value: 300,
      alternatives: ['France', 'Italy', 'Greece', 'Germany'],
      correct: 'Italy',
      state: 'unasked',
    },
    {
      id: 'hi-4',
      question: 'Which ancient civilization built the city of Machu Picchu?',
      question_type: 'text',
      category: 'History',
      value: 400,
      alternatives: ['Aztecs', 'Mayans', 'Incas', 'Toltecs'],
      correct: 'Incas',
      state: 'unasked',
    },
    {
      id: 'hi-5',
      question: 'Who was the longest-reigning British monarch before Queen Elizabeth II?',
      question_type: 'text',
      category: 'History',
      value: 500,
      alternatives: ['King Henry VIII', 'Queen Victoria', 'King George III', 'Queen Elizabeth I'],
      correct: 'Queen Victoria',
      state: 'unasked',
    },
  ],
  isChosen: false,
},
{
  name: 'Chemistry',
  questions: [
    {
      id: 'ch-1',
      question: 'What is the chemical symbol for Gold?',
      question_type: 'text',
      category: 'Chemistry',
      value: 100,
      alternatives: ['Gd', 'Ag', 'Au', 'Fe'],
      correct: 'Au',
      state: 'unasked',
    },
    {
      id: 'ch-2',
      question: 'Which gas do plants absorb from the atmosphere for photosynthesis?',
      question_type: 'text',
      category: 'Chemistry',
      value: 200,
      alternatives: ['Oxygen', 'Nitrogen', 'Carbon Dioxide', 'Hydrogen'],
      correct: 'Carbon Dioxide',
      state: 'unasked',
    },
    {
      id: 'ch-3',
      question: 'What is the pH level of pure water?',
      question_type: 'text',
      category: 'Chemistry',
      value: 300,
      alternatives: ['5', '7', '9', '1'],
      correct: '7',
      state: 'unasked',
    },
    {
      id: 'ch-4',
      question: 'Which element is known as the "building block of life"?',
      question_type: 'text',
      category: 'Chemistry',
      value: 400,
      alternatives: ['Oxygen', 'Nitrogen', 'Carbon', 'Calcium'],
      correct: 'Carbon',
      state: 'unasked',
    },
    {
      id: 'ch-5',
      question: 'What is the most abundant gas in the Earth\'s atmosphere?',
      question_type: 'text',
      category: 'Chemistry',
      value: 500,
      alternatives: ['Oxygen', 'Argon', 'Nitrogen', 'Carbon Dioxide'],
      correct: 'Nitrogen',
      state: 'unasked',
    },
  ],
  isChosen: false,
},
{
  name: 'Physics',
  questions: [
    {
      id: 'ph-1',
      question: 'What force pulls objects toward the center of the Earth?',
      question_type: 'text',
      category: 'Physics',
      value: 100,
      alternatives: ['Magnetism', 'Friction', 'Gravity', 'Inertia'],
      correct: 'Gravity',
      state: 'unasked',
    },
    {
      id: 'ph-2',
      question: 'Which unit is used to measure electrical resistance?',
      question_type: 'text',
      category: 'Physics',
      value: 200,
      alternatives: ['Volt', 'Ampere', 'Watt', 'Ohm'],
      correct: 'Ohm',
      state: 'unasked',
    },
    {
      id: 'ph-3',
      question: 'What is the speed of light in a vacuum approximately?',
      question_type: 'text',
      category: 'Physics',
      value: 300,
      alternatives: ['300,000 km/s', '150,000 km/s', '500,000 km/s', '1,000,000 km/s'],
      correct: '300,000 km/s',
      state: 'unasked',
    },
    {
      id: 'ph-4',
      question: 'According to Newtons Second Law, Force equals Mass times what?',
      question_type: 'text',
      category: 'Physics',
      value: 400,
      alternatives: ['Velocity', 'Acceleration', 'Density', 'Energy'],
      correct: 'Acceleration',
      state: 'unasked',
    },
    {
      id: 'ph-5',
      question: 'Which subatomic particle has no electric charge?',
      question_type: 'text',
      category: 'Physics',
      value: 500,
      alternatives: ['Proton', 'Electron', 'Neutron', 'Positron'],
      correct: 'Neutron',
      state: 'unasked',
    },
  ],
  isChosen: false,
},
{
  name: 'Geography',
  questions: [
    {
      id: 'ge-1',
      question: 'What is the largest continent on Earth?',
      question_type: 'text',
      category: 'Geography',
      value: 100,
      alternatives: ['Africa', 'North America', 'Asia', 'Europe'],
      correct: 'Asia',
      state: 'unasked',
    },
    {
      id: 'ge-2',
      question: 'Which river is the longest in the world?',
      question_type: 'text',
      category: 'Geography',
      value: 200,
      alternatives: ['Amazon', 'Nile', 'Mississippi', 'Yangtze'],
      correct: 'Nile',
      state: 'unasked',
    },
    {
      id: 'ge-3',
      question: 'What is the capital city of Australia?',
      question_type: 'text',
      category: 'Geography',
      value: 300,
      alternatives: ['Sydney', 'Melbourne', 'Canberra', 'Perth'],
      correct: 'Canberra',
      state: 'unasked',
    },
    {
      id: 'ge-4',
      question: 'Which country has the most natural lakes?',
      question_type: 'text',
      category: 'Geography',
      value: 400,
      alternatives: ['USA', 'Canada', 'Russia', 'Brazil'],
      correct: 'Canada',
      state: 'unasked',
    },
    {
      id: 'ge-5',
      question: 'Which mountain range separates Europe and Asia?',
      question_type: 'text',
      category: 'Geography',
      value: 500,
      alternatives: ['The Alps', 'The Himalayas', 'The Andes', 'The Ural Mountains'],
      correct: 'The Ural Mountains',
      state: 'unasked',
    },
  ],
  isChosen: false,
},
{
  name: 'Space',
  questions: [
    {
      id: 'spc-1',
      question: 'Which planet is known as the "Red Planet"?',
      question_type: 'text',
      category: 'Space',
      value: 100,
      alternatives: ['Venus', 'Mars', 'Jupiter', 'Saturn'],
      correct: 'Mars',
      state: 'unasked',
    },
    {
      id: 'spc-2',
      question: 'What is the name of our galaxy?',
      question_type: 'text',
      category: 'Space',
      value: 200,
      alternatives: ['Andromeda', 'Milky Way', 'Sombrero', 'Messier 81'],
      correct: 'Milky Way',
      state: 'unasked',
    },
    {
      id: 'spc-3',
      question: 'Which planet is the largest in our solar system?',
      question_type: 'text',
      category: 'Space',
      value: 300,
      alternatives: ['Saturn', 'Neptune', 'Jupiter', 'Uranus'],
      correct: 'Jupiter',
      state: 'unasked',
    },
    {
      id: 'spc-4',
      question: 'What is the boundary around a black hole from which nothing can escape?',
      question_type: 'text',
      category: 'Space',
      value: 400,
      alternatives: ['Event Horizon', 'Singularity', 'Accretion Disk', 'Oort Cloud'],
      correct: 'Event Horizon',
      state: 'unasked',
    },
    {
      id: 'spc-5',
      question: 'How many moons does the planet Venus have?',
      question_type: 'text',
      category: 'Space',
      value: 500,
      alternatives: ['1', '2', '0', '5'],
      correct: '0',
      state: 'unasked',
    },
  ],
  isChosen: false,
}

];
