export type Question = {
  id: string;
  question: string;
  question_type: 'text' | 'image' | 'video';
  category: string;
  value: number;
  alternatives: string[];
  correct: string;
  state: QuestionState
  image?:string
  video?:string
}

export type QuestionState = 'unasked' | 'right' | 'wrong';

export type QuestionCategory = {
  name: string;
  questions: Question[];
  isChosen: boolean;
  wildCardLocation?:number
}

export const allQuestionCategories: QuestionCategory[] = [
  {
  name: 'TV shows',
  questions: [
    {
      id: 'tv-1',
      question: 'Which iconic sitcom follows the lives of six friends living in Manhattan?',
      question_type: 'text',
      category: 'TV shows',
      value: 100,
      alternatives: [
        'How I Met Your Mother',
        'Friends',
        'Seinfeld',
        'The Big Bang Theory',
      ],
      correct: 'Friends',
      state: 'unasked',
    },
    {
      id: 'tv-2',
      question: 'Which TV show is set in the fictional town of Hawkins?',
      question_type: 'text',
      category: 'TV shows',
      value: 200,
      alternatives: [
        'Dark',
        'Stranger Things',
        'The X-Files',
        'Riverdale',
      ],
      correct: 'Stranger Things',
      state: 'unasked',
    },
    {
      id: 'tv-3',
      question: 'What is the name of the high school chemistry teacher who turns into a meth kingpin in "Breaking Bad"?',
      question_type: 'text',
      category: 'TV shows',
      value: 300,
      alternatives: [
        'Gustavo Fring',
        'Jesse Pinkman',
        'Walter White',
        'Saul Goodman',
      ],
      correct: 'Walter White',
      state: 'unasked',
    },
    {
      id: 'tv-4',
      question: 'Which sci-fi anthology series features stories exploring the dark and often unintended consequences of advanced technology?',
      question_type: 'text',
      category: 'TV shows',
      value: 400,
      alternatives: [
        'Black Mirror',
        'Electric Dreams',
        'Love, Death & Robots',
        'Severance',
      ],
      correct: 'Black Mirror',
      state: 'unasked',
    },
    {
      id: 'tv-5',
      question: 'Which streaming service produced the series “The Crown”?',
      question_type: 'text',
      category: 'TV shows',
      value: 500,
      alternatives: ['Hulu', 'Netflix', 'Amazon Prime', 'HBO'],
      correct: 'Netflix',
      state: 'unasked',
    },
  ],
  isChosen: false,
  },
  {
    name: 'Oscars',
    questions: [
      {
        id: 'os-1',
        question: "For which movie did Leonardo DiCaprio win his first Academy Award?",
        question_type: 'text',
        category: 'Oscars',
        value: 100,
        alternatives: ['The Revenant', 'The Wolf of Wall Street', 'Titanic', 'The Aviator'],
        correct: 'The Revenant',
        state: 'unasked',
      },
      {
        id: 'os-2',
        question: 'Who has won the most Academy Awards for Best Actress?',
        question_type: 'text',
        category: 'Oscars',
        value: 200,
        alternatives: ['Meryl Streep', 'Katharine Hepburn', 'Frances McDormand', 'Bette Davis'],
        correct: 'Katharine Hepburn',
        state: 'unasked',
      },
      {
        id: 'os-3',
        question: 'In 2020, which film became the first non-English language movie to win Best Picture?',
        question_type: 'text',
        category: 'Oscars',
        value: 300,
        alternatives: ['Roma', 'Life is Beautiful', 'Parasite', 'Amour'],
        correct: 'Parasite',
        state: 'unasked',
      },
      {
        id: 'os-4',
        question: 'Which of these films holds the record for the most Oscar nominations (14) without a single win?',
        question_type: 'text',
        category: 'Oscars',
        value: 400,
        alternatives: ['The Color Purple', 'The Turning Point', 'La La Land', 'All About Eve'],
        correct: 'The Turning Point',
        state: 'unasked',
      },
      {
        id: 'os-5',
        question: 'In 1998 Fernanda Montenegro, mother of Fernanda Torres became the first Brazilian and Latin American woman to be nominated for the Academy Award for Best Actress. With what movie was that?',
        question_type: 'image',
        category: 'Oscars',
        image:'fernanda.webp',
        value: 500,
        alternatives: ['Central do Brasil', 'Ainda estou aqui', 'Vitória', 'Senhora do destino'],
        correct: 'Central do Brasil',
        state: 'unasked',
      },
    ],
    isChosen: false,
  },
  {
  name: 'Pop Music',
  questions: [
    {
      id: 'pop-1',
      question: 'Which artist is known as the "King of Pop"?',
      question_type: 'text',
      category: 'Pop Music',
      value: 100,
      alternatives: ['Michael Jackson', 'Elvis Presley', 'Prince', 'Justin Timberlake'],
      correct: 'Michael Jackson',
      state: 'unasked',
    },
    {
      id: 'pop-2',
      question: 'Which singer is famous for the hit song "Shape of You"?',
      question_type: 'text',
      category: 'Pop Music',
      value: 300,
      alternatives: ['Ed Sheeran', 'Bruno Mars', 'Shawn Mendes', 'Adele'],
      correct: 'Ed Sheeran',
      state: 'unasked',
    },
    {
      id: "pop-3",
      question: "Which Katy Perry song shares its title with a 2010 Russell Brand film in which she also makes a cameo?",
      question_type: "text",
      category: "Pop Music",
      value: 400,
      alternatives: ["Teenage Dream", "Firework", "California Gurls", "Hot N Cold"],
      correct: "California Gurls",
      state: "unasked"
    },
    {
      id: 'pop-4',
      question: 'Which pop icon performed at the Super Bowl halftime show in 2020?',
      question_type: 'text',
      category: 'Pop Music',
      value: 400,
      alternatives: ['Jennifer Lopez', 'Shakira', 'Beyoncé', 'Ariana Grande'],
      correct: 'Shakira',
      state: 'unasked',
    },
    {
      id: 'pop-5',
      question: 'Watch this video carefully, then continue the song',
      question_type: 'video',
      video:'https://player.vimeo.com/video/1163299971',
      category: 'Pop Music',
      value: 500,
      alternatives: [
        'Abracadabra, Amor oo na na \n Abra cu da bra, Morta oo gaga \n Abracadabra Abra oo na na', // correct
        'Abracadabra, abadu la ana  \n Abra ca dabra, Ma to u gaga \n Abracadabra, alabu a na',
        'Abra ca dabra, anogu naba \n Abra o cu , na daga \n Abracadabra, oo la la',
        'Abracadabra, ah more na na \n Abra ka dabra, mortal gaga \n Abracadabra, na na na'
      ],
      correct: 'Abracadabra, Amor oo na na \n Abra cu da bra, Morta oo gaga \n Abracadabra Abra oo na na',
      state: 'unasked',
    },
  ],
  isChosen: false,
},
{
  name: 'Video Games',
  questions: [
   {
      id: 'vg-1',
      question: 'Which iconic survival horror series features the "Umbrella Corporation" as its primary antagonist?',
      question_type: 'text',
      category: 'Video Games',
      value: 100,
      alternatives: ['Silent Hill', 'Resident Evil', 'Dead Space', 'BioShock'],
      correct: 'Resident Evil',
      state: 'unasked',
    },
    {
      id: 'vg-2',
      question: 'In which game do players compete in a battle royale on an island and can build platforms?',
      question_type: 'text',
      category: 'Video Games',
      value: 200,
      alternatives: ['Fortnite', 'Call of Duty', 'PUBG', 'Apex Legends'],
      correct: 'Fortnite',
      state: 'unasked',
    },
    {
      id: 'vg-3',
      question: 'In which game is the player character known as "The Dark World"?',
      question_type: 'text',
      category: 'Video Games',
      value: 300,
      alternatives: ['Hyrule', 'Tamriel', 'Azeroth', 'Kanto'],
      correct: 'Hyrule',
      state: 'unasked',
    },
    
    {
      id: 'vg-4',
      question: 'Which video game series features the character Master Chief?',
      question_type: 'text',
      category: 'Video Games',
      value: 400,
      alternatives: ['Halo', 'Destiny', 'Gears of War', 'Mass Effect'],
      correct: 'Halo',
      state: 'unasked',
    },
    {
      id: 'vg-5',
      question: 'In the Legend of Zelda series, what is the name of the parallel world featured in "A Link to the Past"?',
      question_type: 'text',
      category: 'Video Games',
      value: 500,
      alternatives: ['The Twilight Realm', 'The End', 'The Dark World', 'Termina'],
      correct: 'The Dark World',
      state: 'unasked',
    },
  ],
  isChosen: false,
},
{
    name: 'Warhammer 40k',
    questions: [
      {
        id: 'wh-1',
        question: 'Who is the immortal ruler and god of the Imperium of Man?',
        question_type: 'text',
        category: 'Warhammer 40k',
        value: 100,
        alternatives: ['Horus Lupercal', 'The Emperor of Mankind', 'Roboute Guilliman', 'Malcador the Sigillite'],
        correct: 'The Emperor of Mankind',
        state: 'unasked',
      },
      {
        id: 'wh-2',
        question: 'Which Primarch turned traitor and led the siege on Holy Terra?',
        question_type: 'text',
        category: 'Warhammer 40k',
        value: 200,
        alternatives: ['Leman Russ', 'Horus Lupercal', 'Sanguinius', 'Rogal Dorn'],
        correct: 'Horus Lupercal',
        state: 'unasked',
      },
      {
        id: 'wh-3',
        question: 'The Space Marine Chapter known as the "Blood Angels" suffers from which genetic flaw?',
        question_type: 'text',
        category: 'Warhammer 40k',
        value: 300,
        alternatives: ['The Black Rage', 'The Wulfen', 'The Flesh Change', 'The Red Thirst'],
        correct: 'The Black Rage',
        state: 'unasked',
      },
      {
        id: 'wh-4',
        question: 'What is the name of the mechanical, skeletal xenos race that seeks to reclaim their ancient empire?',
        question_type: 'text',
        category: 'Warhammer 40k',
        value: 400,
        alternatives: ['Aeldari', 'Tyranids', 'Necrons', 'T’au'],
        correct: 'Necrons',
        state: 'unasked',
      },
      {
        id: 'wh-5',
        question: 'Which Chaos God is known as the Blood God and the Lord of Skulls?',
        question_type: 'text',
        category: 'Warhammer 40k',
        value: 500,
        alternatives: ['Tzeentch', 'Nurgle', 'Slaanesh', 'Khorne'],
        correct: 'Khorne',
        state: 'unasked',
      },
    ],
    isChosen: false,
  },
  {
  name: 'Sports',
  questions: [
    {
      id: 'sp-1',
      question: 'In which sport would you use a "shuttlecock"?',
      question_type: 'text',
      category: 'Sports',
      value: 100,
      alternatives: ['Tennis', 'Badminton', 'Table Tennis', 'Squash'],
      correct: 'Badminton',
      state: 'unasked',
    },
    {
      id: 'sp-2',
      question: 'Which country has won the most FIFA World Cups?',
      question_type: 'text',
      category: 'Sports',
      value: 200,
      alternatives: ['Germany', 'Argentina', 'Brazil', 'Italy'],
      correct: 'Brazil',
      state: 'unasked',
    },
    {
      id: 'sp-3',
      question: 'Which NHL team has won the most Stanley Cups?',
      question_type: 'text',
      category: 'Sports',
      value: 300,
      alternatives: ['Montréal Canadiens', 'Toronto Maple Leafs', 'Detroit Red Wings', 'Florida Panthers'],
      correct: 'Montréal Canadiens',
      state: 'unasked',
    },
    {
      id: 'sp-4',
      question: 'How many minutes is a standard professional rugby union match?',
      question_type: 'text',
      category: 'Sports',
      value: 400,
      alternatives: ['90 minutes', '80 minutes', '70 minutes', '60 minutes'],
      correct: '80 minutes',
      state: 'unasked',
    },
    {
      id: 'sp-5',
      question: 'Which golf tournament awards the winner a "Green Jacket"?',
      question_type: 'text',
      category: 'Sports',
      value: 500,
      alternatives: ['The U.S. Open', 'The Open Championship', 'PGA Championship', 'The Masters'],
      correct: 'The Masters',
      state: 'unasked',
    },
  ],
  isChosen: false,
},
{
  name: 'History',
  questions: [
    {
      id: 'hi-1',
      question: 'Who was the first President of the United States?',
      question_type: 'text',
      category: 'History',
      value: 100,
      alternatives: ['Thomas Jefferson', 'Abraham Lincoln', 'George Washington', 'John Adams'],
      correct: 'George Washington',
      state: 'unasked',
    },
    {
      id: 'hi-2',
      question: 'In what year did the Titanic sink?',
      question_type: 'text',
      category: 'History',
      value: 200,
      alternatives: ['1912', '1905', '1920', '1898'],
      correct: '1912',
      state: 'unasked',
    },
    {
      id: 'hi-3',
      question: 'The Renaissance period began in which European country?',
      question_type: 'text',
      category: 'History',
      value: 300,
      alternatives: ['France', 'Italy', 'Greece', 'Germany'],
      correct: 'Italy',
      state: 'unasked',
    },
    {
      id: 'hi-4',
      question: 'Which ancient civilization built the city of Machu Picchu?',
      question_type: 'text',
      category: 'History',
      value: 400,
      alternatives: ['Aztecs', 'Mayans', 'Incas', 'Toltecs'],
      correct: 'Incas',
      state: 'unasked',
    },
    {
      id: 'hi-5',
      question: 'Who was the longest-reigning British monarch before Queen Elizabeth II?',
      question_type: 'text',
      category: 'History',
      value: 500,
      alternatives: ['King Henry VIII', 'Queen Victoria', 'King George III', 'Queen Elizabeth I'],
      correct: 'Queen Victoria',
      state: 'unasked',
    },
  ],
  isChosen: false,
},
{
  name: 'Chemistry',
  questions: [
    {
      id: 'ch-1',
      question: 'What is the chemical symbol for Gold?',
      question_type: 'text',
      category: 'Chemistry',
      value: 100,
      alternatives: ['Gd', 'Ag', 'Au', 'Fe'],
      correct: 'Au',
      state: 'unasked',
    },
    {
      id: 'ch-2',
      question: 'Which gas do plants absorb from the atmosphere for photosynthesis?',
      question_type: 'text',
      category: 'Chemistry',
      value: 200,
      alternatives: ['Oxygen', 'Nitrogen', 'Carbon Dioxide', 'Hydrogen'],
      correct: 'Carbon Dioxide',
      state: 'unasked',
    },
    {
      id: 'ch-3',
      question: 'What is the pH level of pure water?',
      question_type: 'text',
      category: 'Chemistry',
      value: 300,
      alternatives: ['5', '7', '9', '1'],
      correct: '7',
      state: 'unasked',
    },
    {
      id: 'ch-4',
      question: 'Which element is known as the "building block of life"?',
      question_type: 'text',
      category: 'Chemistry',
      value: 400,
      alternatives: ['Oxygen', 'Nitrogen', 'Carbon', 'Calcium'],
      correct: 'Carbon',
      state: 'unasked',
    },
    {
      id: 'ch-5',
      question: 'What is that?',
      question_type: 'image',
      image: 'etanol.jpg',
      category: 'Chemistry',
      value: 500,
      alternatives: ['Chlorophyll', 'Methane Gas', 'The Atomic bomb formula', 'Alcohol'],
      correct: 'Alcohol',
      state: 'unasked',
    },
  ],
  isChosen: false,
},
{
  name: 'Physics',
  questions: [
    {
      id: 'ph-1',
      question: 'What force pulls objects toward the center of the Earth?',
      question_type: 'text',
      category: 'Physics',
      value: 100,
      alternatives: ['Magnetism', 'Friction', 'Gravity', 'Inertia'],
      correct: 'Gravity',
      state: 'unasked',
    },
    {
      id: 'ph-2',
      question: 'Which unit is used to measure electrical resistance?',
      question_type: 'text',
      category: 'Physics',
      value: 200,
      alternatives: ['Volt', 'Ampere', 'Watt', 'Ohm'],
      correct: 'Ohm',
      state: 'unasked',
    },
    {
      id: 'ph-3',
      question: 'What is the speed of light in a vacuum approximately?',
      question_type: 'text',
      category: 'Physics',
      value: 300,
      alternatives: ['300,000 km/s', '150,000 km/s', '500,000 km/s', '1,000,000 km/s'],
      correct: '300,000 km/s',
      state: 'unasked',
    },
    {
      id: 'ph-4',
      question: 'According to Newtons Second Law, Force equals Mass times what?',
      question_type: 'text',
      category: 'Physics',
      value: 400,
      alternatives: ['Velocity', 'Acceleration', 'Density', 'Energy'],
      correct: 'Acceleration',
      state: 'unasked',
    },
    {
      id: 'ph-5',
      question: 'Which subatomic particle has no electric charge?',
      question_type: 'text',
      category: 'Physics',
      value: 500,
      alternatives: ['Proton', 'Electron', 'Neutron', 'Positron'],
      correct: 'Neutron',
      state: 'unasked',
    },
  ],
  isChosen: false,
},
{
  name: 'Geography',
  questions: [
    {
      id: 'ge-1',
      question: 'What is the largest continent on Earth?',
      question_type: 'text',
      category: 'Geography',
      value: 100,
      alternatives: ['Africa', 'North America', 'Asia', 'Europe'],
      correct: 'Asia',
      state: 'unasked',
    },
    {
      id: 'ge-2',
      question: 'Which river is the longest in the world?',
      question_type: 'text',
      category: 'Geography',
      value: 200,
      alternatives: ['Amazon', 'Nile', 'Mississippi', 'Yangtze'],
      correct: 'Nile',
      state: 'unasked',
    },
    {
      id: 'ge-3',
      question: 'What is the capital city of Australia?',
      question_type: 'text',
      category: 'Geography',
      value: 300,
      alternatives: ['Sydney', 'Melbourne', 'Canberra', 'Perth'],
      correct: 'Canberra',
      state: 'unasked',
    },
    {
      id: 'ge-4',
      question: 'Which country has the most natural lakes?',
      question_type: 'text',
      category: 'Geography',
      value: 400,
      alternatives: ['USA', 'Canada', 'Russia', 'Brazil'],
      correct: 'Canada',
      state: 'unasked',
    },
    {
      id: 'ge-5',
      question: 'Which mountain range separates Europe and Asia?',
      question_type: 'text',
      category: 'Geography',
      value: 500,
      alternatives: ['The Alps', 'The Himalayas', 'The Andes', 'The Ural Mountains'],
      correct: 'The Ural Mountains',
      state: 'unasked',
    },
  ],
  isChosen: false,
},
{
  name: 'Biology',
  questions: [
    {
      id: 'bi-1',
      question: 'What is known as the powerhouse of the cell?',
      question_type: 'text',
      category: 'Biology',
      value: 100,
      alternatives: ['Nucleus', 'Ribosome', 'Mitochondria', 'Chloroplast'],
      correct: 'Mitochondria',
      state: 'unasked',
    },
    {
      id: 'bi-2',
      question: 'Which protein in red blood cells carries oxygen throughout the body?',
      question_type: 'text',
      category: 'Biology',
      value: 200,
      alternatives: ['Insulin', 'Hemoglobin', 'Collagen', 'Keratin'],
      correct: 'Hemoglobin',
      state: 'unasked',
    },
    {
      id: 'bi-3',
      question: 'What is the process by which plants convert sunlight into chemical energy?',
      question_type: 'text',
      category: 'Biology',
      value: 300,
      alternatives: ['Respiration', 'Fermentation', 'Photosynthesis', 'Transpiration'],
      correct: 'Photosynthesis',
      state: 'unasked',
    },
    {
      id: 'bi-4',
      question: 'How many pairs of chromosomes do humans typically have in each cell?',
      question_type: 'text',
      category: 'Biology',
      value: 400,
      alternatives: ['20', '23', '46', '12'],
      correct: '23',
      state: 'unasked',
    },
    {
      id: 'bi-5',
      question: 'Which Dutch scientist is often referred to as the "Father of Microbiology" for his work with microscopes?',
      question_type: 'text',
      category: 'Biology',
      value: 500,
      alternatives: ['Louis Pasteur', 'Robert Hooke', 'Gregor Mendel', 'Antonie van Leeuwenhoek'],
      correct: 'Antonie van Leeuwenhoek',
      state: 'unasked',
    },
  ],
  isChosen: false,
},
{
  name: 'Space',
  questions: [
    {
      id: 'spc-1',
      question: 'Which planet is known as the "Red Planet"?',
      question_type: 'text',
      category: 'Space',
      value: 100,
      alternatives: ['Venus', 'Mars', 'Jupiter', 'Saturn'],
      correct: 'Mars',
      state: 'unasked',
    },
    {
      id: 'spc-2',
      question: 'What is the name of our galaxy?',
      question_type: 'text',
      category: 'Space',
      value: 200,
      alternatives: ['Andromeda', 'Milky Way', 'Sombrero', 'Messier 81'],
      correct: 'Milky Way',
      state: 'unasked',
    },
    {
      id: 'spc-3',
      question: 'Which planet is the largest in our solar system?',
      question_type: 'text',
      category: 'Space',
      value: 300,
      alternatives: ['Saturn', 'Neptune', 'Jupiter', 'Uranus'],
      correct: 'Jupiter',
      state: 'unasked',
    },
    {
      id: 'spc-4',
      question: 'What is the boundary around a black hole from which nothing can escape?',
      question_type: 'text',
      category: 'Space',
      value: 400,
      alternatives: ['Event Horizon', 'Singularity', 'Accretion Disk', 'Oort Cloud'],
      correct: 'Event Horizon',
      state: 'unasked',
    },
    {
      id: 'spc-5',
      question: 'How many moons does the planet Venus have?',
      question_type: 'text',
      category: 'Space',
      value: 500,
      alternatives: ['1', '2', '0', '5'],
      correct: '0',
      state: 'unasked',
    },
  ],
  isChosen: false,
},
{
  name: 'Food',
  questions: [
   {
      id: 'fd-1',
      question: 'In which US city were Buffalo wings famously invented?',
      question_type: 'text',
      category: 'Food',
      value: 100,
      alternatives: ['New York City', 'Albany', 'Buffalo', 'Rochester'],
      correct: 'Buffalo',
      state: 'unasked',
    },
    {
      id: 'fd-2',
      question: 'In which city was the Caesar Salad famously invented during a Fourth of July rush in 1924?',
      question_type: 'text',
      category: 'Food',
      value: 200,
      alternatives: ['San Diego', 'Tijuana', 'Chicago', 'Montreal'],
      correct: 'Tijuana',
      state: 'unasked',
    },
    {
      id: 'fd-3',
      question: 'What is the main ingredient in traditional Japanese Miso soup?',
      question_type: 'text',
      category: 'Food',
      value: 300,
      alternatives: ['Fermented Soybeans', 'Rice Flour', 'Seaweed Extract', 'Tofu'],
      correct: 'Fermented Soybeans',
      state: 'unasked',
    },
    {
      id: 'fd-4',
      question: 'What kind of cheese is traditionally used in Cooper\'s Hill Cheese-Rolling?',
      question_type: 'image',
      category: 'Food',
      image: 'cheese-roll.webp',
      value: 400,
      alternatives: ['Duddleswell', 'Hereford Hop', 'Double Gloucester', 'Stinking Bishop'],
      correct: 'Double Gloucester',
      state: 'unasked',
    },
    {
      id: 'fd-5',
      question: 'Which expensive spice is derived from the flower of the Crocus sativus?',
      question_type: 'text',
      category: 'Food',
      value: 500,
      alternatives: ['Vanilla', 'Saffron', 'Cardamom', 'Cinnamon'],
      correct: 'Saffron',
      state: 'unasked',
    },
  ],
  isChosen: false,
},
{
  name: 'Animal Kingdom',
  questions: [
    {
      id: 'ak-1',
      question: 'What canadian animal is famous for building dams?',
      question_type: 'text',
      category: 'Animal Kingdom',
      value: 100,
      alternatives: ['Moose', 'Grizzly Bear', 'Beaver', 'Walrus'],
      correct: 'Beaver',
      state: 'unasked',
    },
    {
      id: 'ak-2',
      question: 'What is the largest animal ever known to have existed?',
      question_type: 'text',
      category: 'Animal Kingdom',
      value: 200,
      alternatives: ['African Elephant', 'Blue Whale', 'Colossal Squid', 'Megatherium'],
      correct: 'Blue Whale',
      state: 'unasked',
    },
    {
      id: 'ak-3',
      question: 'Which large, antlered animal is the official national symbol of Canada and is known to be the largest member of the deer family?',
      question_type: 'text',
      category: 'Animal Kingdom',
      value: 300,
      alternatives: ['Moose', 'Elk', 'Caribou', 'White-tailed Deer'],
      correct: 'Moose',
      state: 'unasked',
    },
    {
      id: 'ak-4',
      question: 'Which one of these flightless birds is native only to New Zealand',
      question_type: 'text',
      category: 'Animal Kingdom',
      value: 400,
      alternatives: ['Emu', 'Ostrich', 'Kiwi', 'Cassowary'],
      correct: 'Kiwi',
      state: 'unasked',
    },
    {
      id: 'ak-5',
      question: 'Which of these marine animals is technically considered "immortal" due to its ability to revert its cells to a youthful state?',
      question_type: 'text',
      category: 'Animal Kingdom',
      value: 500,
      alternatives: ['Green Sea Turtle', 'Turritopsis dohrnii (Jellyfish)', 'Axolotl', 'Bowhead Whale'],
      correct: 'Turritopsis dohrnii (Jellyfish)',
      state: 'unasked',
    },
  ],
  isChosen: false,
},
{
  name: 'Harry Potter',
  questions: [
    {
      id: 'hp-1',
      question: 'Which house at Hogwarts is known for valuing bravery, daring, and chivalry?',
      question_type: 'image',
      category: 'Harry Potter',
      image: 'hogwarts-crests.jpg',
      value: 100,
      alternatives: ['Hufflepuff', 'Ravenclaw', 'Slytherin', 'Gryffindor'],
      correct: 'Gryffindor',
      state: 'unasked',
    },
    {
      id: 'hp-2',
      question: 'What is the name of the train that transports students from Platform 9¾ to Hogwarts?',
      question_type: 'text',
      category: 'Harry Potter',
      value: 200,
      alternatives: ['The Knight Bus', 'The Hogwarts Express', 'The Hogsmeade Flyer', 'The Durmstrang Ship'],
      correct: 'The Hogwarts Express',
      state: 'unasked',
    },
    {
      id: 'hp-3',
      question: 'Which of these is NOT one of the three Deathly Hallows?',
      question_type: 'text',
      category: 'Harry Potter',
      value: 300,
      alternatives: ['The Elder Wand', 'The Invisibility Cloak', 'The Resurrection Stone', 'The Sorcerer’s Stone'],
      correct: 'The Sorcerer’s Stone',
      state: 'unasked',
    },
    {
      id: 'hp-4',
      question: 'To enter the common room of this house, you must solve a riddle rather than provide a password. Which house is it?',
      question_type: 'image',
      category: 'Harry Potter',
      image: 'hogwarts-crests.jpg',
      value: 400,
      alternatives: ['Ravenclaw', 'Slytherin', 'Hufflepuff', 'Gryffindor'],
      correct: 'Ravenclaw',
      state: 'unasked',
    },
    {
      id: 'hp-5',
      question: 'What is the name of the plant that Neville Longbottom receives as a gift, which helps him regain his confidence in Herbology?',
      question_type: 'text',
      category: 'Harry Potter',
      value: 500,
      alternatives: ['Mandrake', 'Devil’s Snare', 'Mimbulus mimbletonia', 'Bubotuber'],
      correct: 'Mimbulus mimbletonia',
      state: 'unasked',
    },
  ],
  isChosen: false,
},
{
  name: 'Tech Bros and Crypto Sh*t',
  questions: [
    {
      id: 'tc-1',
      question: 'Which cryptocurrency, represented by a Japanese Shiba Inu, started as a joke but became a multi-billion dollar asset?',
      question_type: 'image',
      category: 'Tech Bros and Crypto Sh*t',
      image: 'doge-coin.webp',
      value: 100,
      alternatives: ['Barkcoin', 'Shibacoin', 'Dogecoin', 'Dogcoin'],
      correct: 'Dogecoin',
      state: 'unasked',
    },
    {
      id: 'tc-2',
      question: 'Which "Tech Bro" famously rebranded his entire social media empire to "Meta" to focus on a virtual reality future?',
      question_type: 'text',
      category: 'Tech Bros and Crypto Sh*t',
      value: 200,
      alternatives: ['Elon Musk', 'Jack Dorsey', 'Mark Zuckerberg', 'Jeff Bezos'],
      correct: 'Mark Zuckerberg',
      state: 'unasked',
    },
    {
      id: 'tc-3',
      question: 'Which cryptocurrency caused controversy in Argentina after being promoted by President Javier Milei?',
      question_type: 'text',
      category: 'Tech Bros and Crypto Sh*t',
      value: 300,
      alternatives: ['$Buena', '$Libra', '$Luna', '$Solana'],
      correct: '$Libra',
      state: 'unasked',
    },
    {
      id: 'tc-4',
      question: 'Who is the pseudonymous creator of Bitcoin, whose true identity remains one of the biggest mysteries in tech?',
      question_type: 'text',
      category: 'Tech Bros and Crypto Sh*t',
      value: 400,
      alternatives: ['Vitalik Buterin', 'Satoshi Nakamoto', 'Sam Bankman-Fried', 'Craig Wright'],
      correct: 'Satoshi Nakamoto',
      state: 'unasked',
    },
    {
      id: 'tc-5',
      question: 'In the world of crypto-collectibles, what does the acronym "NFT" actually stand for?',
      question_type: 'text',
      category: 'Tech Bros and Crypto Sh*t',
      value: 500,
      alternatives: ['Non-Fungible Token', 'Net-Fractional Transfer', 'Node-Formulated Token', 'Non-Fungible Transaction'],
      correct: 'Non-Fungible Token',
      state: 'unasked',
    },
  ],
  isChosen: false,
},
{
name: 'Broadway Musicals',
questions: [
  {
    id: 'bm-1',
    question: 'Which record-breaking musical features the story of the founding father who served as the first U.S. Secretary of the Treasury?',
    question_type: 'text',
    category: 'Broadway Musicals',
    value: 100,
    alternatives: ['Hamilton', '1776', 'Jefferson', 'Founding'],
    correct: 'Hamilton',
    state: 'unasked',
  },
  {
    id: 'bm-2',
    question: 'Often called the "wicked" untold story of the Witches of Oz, what is the name of this massive Broadway hit?',
    question_type: 'image',
    category: 'Broadway Musicals',
    image: 'wicked-logo.webp',
    value: 200,
    alternatives: ['The Wizard', 'Wicked', 'Emerald City', 'Glinda'],
    correct: 'Wicked',
    state: 'unasked',
  },
  {
    id: 'bm-3',
    question: 'Which Andrew Lloyd Webber musical, based on T.S. Eliot’s poetry, was one of the longest-running shows in Broadway history?',
    question_type: 'text',
    category: 'Broadway Musicals',
    value: 300,
    alternatives: ['Phantom of the Opera', 'Cats', 'Starlight Express', 'Evita'],
    correct: 'Cats',
    state: 'unasked',
  },
  {
    id: 'bm-4',
    question: 'What is the name of the long-running musical that features a French revolution setting and includes the iconic song "I Dreamed a Dream"?',
    question_type: 'text',
    category: 'Broadway Musicals',
    value: 400,
    alternatives: ['Les Misérables', 'The Hunchback of Notre Dame', 'Moulin Rouge', 'A Tale of Two Cities'],
    correct: 'Les Misérables',
    state: 'unasked',
  },
  {
    id: 'bm-5',
    question: 'Which Tony Award-winning musical by Jonathan Larson is a modern retelling of the opera La Bohème set in New York City?',
    question_type: 'text',
    category: 'Broadway Musicals',
    value: 500,
    alternatives: ['Rent', 'Hair', 'Company', 'In the Heights'],
    correct: 'Rent',
    state: 'unasked',
  }
  ],
  isChosen: false,
},
{
name: "Cats Facts",
questions: [
  {
    id: 'cf-1',
    question: 'Approximately how many hours per day do the average house cats spend sleeping?',
    question_type: 'text',
    category: 'Cats Facts',
    value: 100,
    alternatives: ['4-6 hours', '8-10 hours', '12-16 hours', '18-20 hours'],
    correct: '12-16 hours',
    state: 'unasked',
  },
  {
    id: 'cf-2',
    question: 'What is the technical term for a group of kittens?',
    question_type: 'text',
    category: 'Cats Facts',
    value: 200,
    alternatives: ['A litter', 'A kindle', 'A cluster', 'A brood'],
    correct: 'A kindle',
    state: 'unasked',
  },
  {
    id: 'cf-3',
    question: 'Where was the first Cat`s and Pedro`s date?',
    question_type: 'text',
    category: 'Cats Facts',
    value: 300,
    alternatives: ['La Latina', 'Rio 40', 'Good Fortune', 'Storm Crow Manor'],
    correct: 'Good Fortune',
    state: 'unasked',
  },
  {
    id: 'cf-4',
    question: 'Which of these is the world’s largest cat breed, often nicknamed "the gentle giant"?',
    question_type: 'image',
    category: 'Cats Facts',
    image: 'maine-coon.webp',
    value: 400,
    alternatives: ['Bengal', 'Ragdoll', 'Maine Coon', 'Persian'],
    correct: 'Maine Coon',
    state: 'unasked',
  },
  {
    id: 'cf-5',
    question: 'What was the name of Lulu before coming to Canada?',
    question_type: 'text',
    category: 'Cats Facts',
    value: 500,
    alternatives: ['Haykku', 'Lustiana', 'Hekiyo', 'Heiko'],
    correct: 'Hekiyo',
    state: 'unasked',
  }
],
isChosen: false,
},
{
name: 'Cartoons',
questions: [
{
id: 'ct-1',
question: 'Which legendary cartoon duo is famous for their perpetual and violent chase involving anvils and ACME products?',
question_type: 'text',
category: 'Cartoons',
value: 100,
alternatives: ['Tom and Jerry', 'Wile E. Coyote and Road Runner', 'Sylvester and Tweety', 'Itchy and Scratchy'],
correct: 'Wile E. Coyote and Road Runner',
state: 'unasked',
},
{
id: 'ct-2',
question: 'In "SpongeBob SquarePants," what is the name of the fast-food restaurant where SpongeBob works as a fry cook?',
question_type: 'text',
category: 'Cartoons',
value: 200,
alternatives: ['The Chum Bucket', 'The Krusty Krab', 'The Salty Spitoon', 'Bikini Bottom Grill'],
correct: 'The Krusty Krab',
state: 'unasked',
},
{
id: 'ct-3',
question: 'What is the full name of the boy who owns the dog "Scooby-Doo" in the original Hanna-Barbera series?',
question_type: 'text',
category: 'Cartoons',
value: 300,
alternatives: ['Fred Jones', 'Shaggy Rogers', 'Norville Rogers', 'Daphne Blake'],
correct: 'Norville Rogers',
state: 'unasked',
},
{
id: 'ct-4',
question: 'In the animated series "Avatar: The Last Airbender," what is the name of Aang`s winged lemur companion?',
question_type: 'text',
category: 'Cartoons',
value: 400,
alternatives: ['Appa', 'Momo', 'Pabu', 'Naga'],
correct: 'Momo',
state: 'unasked',
},
{
id: 'ct-5',
question: 'In the original "ThunderCats" series, what is the name of the ancient, evil sorcerer who serves as the primary antagonist of Lion-O?',
question_type: 'text',
category: 'Cartoons',
value: 500,
alternatives: ['Mum-Ra', 'Skeletor', 'Megatron', 'Venger'],
correct: 'Mum-Ra',
state: 'unasked',
},
],
isChosen: false,
},
{
name: 'Reality TV',
questions: [
  {
    id: 'rtv-1',
    question: 'Which reality competition series is famously known for its "Tribal Council" and the goal to "Outwit, Outplay, Outlast"?',
    question_type: 'text',
    category: 'Reality TV',
    value: 100,
    alternatives: ['The Amazing Race', 'Survivor', 'Big Brother', 'Alone'],
    correct: 'Survivor',
    state: 'unasked',
  },
  {
    id: 'rtv-2',
    question: 'In "The Bachelor," what color is the final rose that indicates a contestant is moving on to the next round?',
    question_type: 'text',
    category: 'Reality TV',
    value: 200,
    alternatives: ['White', 'Red', 'Yellow', 'Pink'],
    correct: 'Red',
    state: 'unasked',
  },
  {
    id: 'rtv-3',
    question: 'Which professional chef hosts "Hell`s Kitchen" and is known for his strict standards and fiery temper?',
    question_type: 'text',
    category: 'Reality TV',
    value: 300,
    alternatives: ['Bobby Flay', 'Gordon Ramsay', 'Jamie Oliver', 'Guy Fieri'],
    correct: 'Gordon Ramsay',
    state: 'unasked',
  },
  {
    id: 'rtv-4',
    question: 'Which city hosted the first installment of "The Real Housewives" franchise in 2006?',
    question_type: 'text',
    category: 'Reality TV',
    value: 400,
    alternatives: ['Orange County', 'Beverly Hills', 'Atlanta', 'New York City'],
    correct: 'Orange County',
    state: 'unasked',
  },
  {
    id: 'rtv-5',
    question: 'Which television personality coined the term "smize" on "America`s Next Top Model"?',
    question_type: 'text',
    category: 'Reality TV',
    value: 500,
    alternatives: ['Heidi Klum', 'Naomi Campbell', 'Tyra Banks', 'Kate Moss'],
    correct: 'Tyra Banks',
    state: 'unasked',
  },
],
isChosen: false,
},
{
  name: 'Anime',
  questions: [
    {
      id: 'an-1',
      question: 'What anime is this girl from?',
      question_type: 'image',
      image: 'anime-girl.png',
      category: 'Anime',
      value: 100,
      alternatives: ['My-HiME', 'Sakura Cardcaptor', 'Sailor Moon', 'Cowboy Bebop'],
      correct: 'Sailor Moon',
      state: 'unasked',
    },
    {
      id: 'an-2',
      question: 'In "Death Note," what must you know to kill someone using the notebook?',
      question_type: 'text',
      category: 'Anime',
      value: 200,
      alternatives: ['Their birthday', 'Their face and name', 'Their location', 'Their blood type'],
      correct: 'Their face and name',
      state: 'unasked',
    },
    {
      id: 'an-3',
      question: 'In Fullmetal Alchemist, what is the biggest alchemy taboo?',
      question_type: 'text',
      category: 'Anime',
      value: 300,
      alternatives: ['Human transmutation', 'Testing in animals', 'The philosopher`s stone', 'Creating life'],
      correct: 'Human Transmutation',
      state: 'unasked',
    },
   {
    id: 'an-4',
    question: 'In Attack on Titan, what is the name of the device soldiers use to move through the air while fighting Titans?',
    question_type: 'image',
    image:'3d-maneuver-gear.png',
    category: 'Anime',
    value: 400,
    alternatives: ['3D Maneuver Gear', 'Titan Harness', 'Vertical Gear', 'Aerial Mobility Pack'],
    correct: '3D Maneuver Gear',
    state: 'unasked',
  },
    {
      id: 'an-5',
      question: 'Which Studio Ghibli film features a bathhouse for spirits run by the witch Yubaba?',
      question_type: 'text',
      category: 'Anime',
      value: 500,
      alternatives: ['Princess Mononoke', 'My Neighbor Totoro', 'Howl\'s Moving Castle', 'Spirited Away'],
      correct: 'Spirited Away',
      state: 'unasked',
    },
  ],
  isChosen: false,
},
{
  name: 'Mythology',
  questions: [
    {
      id: 'my-1',
      question: 'Who is the king of the Greek gods?',
      question_type: 'text',
      category: 'Mythology',
      value: 100,
      alternatives: ['Hades', 'Poseidon', 'Zeus', 'Apollo'],
      correct: 'Zeus',
      state: 'unasked',
    },
    {
      id: 'my-2',
      question: 'In Norse mythology, what is the name of Thor’s hammer?',
      question_type: 'text',
      category: 'Mythology',
      value: 200,
      alternatives: ['Gungnir', 'Mjolnir', 'Excalibur', 'Gram'],
      correct: 'Mjolnir',
      state: 'unasked',
    },
    {
      id: 'my-3',
      question: 'Which Egyptian god is associated with the afterlife and is often depicted with a jackal head?',
      question_type: 'text',
      category: 'Mythology',
      value: 300,
      alternatives: ['Ra', 'Osiris', 'Anubis', 'Horus'],
      correct: 'Anubis',
      state: 'unasked',
    },
    {
      id: 'my-4',
      question: 'In Egyptian mythology, who is the god of chaos that murdered Osiris?',
      question_type: 'text',
      category: 'Mythology',
      value: 400,
      alternatives: ['Set', 'Horus', 'Thoth', 'Ptah'],
      correct: 'Set',
      state: 'unasked',
    },
    {
      id: 'my-5',
      question: 'In Aztec mythology, which god is associated with the Feathered Serpent?',
      question_type: 'text',
      category: 'Mythology',
      value: 500,
      alternatives: ['Huitzilopochtli', 'Tezcatlipoca', 'Quetzalcoatl', 'Tlaloc'],
      correct: 'Quetzalcoatl',
      state: 'unasked',
    },
  ],
  isChosen: false,
},
{
  name: 'Brazilian Culture',
  questions: [
    {
      id: 'br-1',
      question: 'What is the largest city in Brazil?',
      question_type: 'text',
      category: 'Brazilian Culture',
      value: 100,
      alternatives: ['Rio de Janeiro', 'Brasília', 'São Paulo', 'Salvador'],
      correct: 'São Paulo',
      state: 'unasked',
    },
    {
      id: 'br-2',
      question: 'Which Brazilian festival is famous for its parades, samba, and costumes?',
      question_type: 'text',
      category: 'Brazilian Culture',
      value: 200,
      alternatives: ['Festa Junina', 'Carnival', 'Bumba Meu Boi', 'Oktoberfest'],
      correct: 'Carnival',
      state: 'unasked',
    },
    {
      id: 'br-3',
      question: 'Which Afro-Brazilian religious tradition blends Yoruba beliefs with Catholic elements and is especially strong in Bahia?',
      question_type: 'text',
      category: 'Brazilian Culture',
      value: 300,
      alternatives: ['Candomblé', 'Umbanda', 'Santo Daime', 'Xangô'],
      correct: 'Candomblé',
      state: 'unasked',
    },
    {
      id: 'br-4',
      question: 'In Brazilian folklore, who is the one-legged trickster who wears a red cap and creates mischief in the forest?',
      question_type: 'image',
      category: 'Brazilian Culture',
      image: 'saci.png',
      value: 400,
      alternatives: ['Curupira', 'Saci-Pererê', 'Boitatá', 'Iara'],
      correct: 'Saci-Pererê',
      state: 'unasked',
    },
    {
      id: 'br-5',
      question: 'Which brazilian artist painted this famous work?',
      question_type: 'image',
      category: 'Brazilian Culture',
      image: 'abaporu.jpg',
      value: 500,
      alternatives: ['Candido Portinari', 'Tarsila do Amaral', 'Anita Malfatti', 'Romeiro Britto'],
      correct: 'Tarsila do Amaral',
      state: 'unasked',
    },
  ],
  isChosen: false,
},
{
  name: 'Toronto Blue Jays',
  questions: [
    {
      id: 'bj-1',
      question: 'What is the name of the Blue Jays official mascot?',
      question_type: 'text',
      category: 'Toronto Blue Jays',
      value: 100,
      alternatives: ['Slider', 'Ace', 'Raymond', 'Wally'],
      correct: 'Ace',
      state: 'unasked',
    },
    {
      id: 'bj-2',
      question: 'The Blue Jays won back-to-back World Series titles in which two years?',
      question_type: 'text',
      category: 'Toronto Blue Jays',
      value: 200,
      alternatives: ['1985 & 1986', '1991 & 1992', '1992 & 1993', '1993 & 1994'],
      correct: '1992 & 1993',
      state: 'unasked',
    },
    {
      id: 'bj-3',
      question: "Which stadium has been the home of the Blue Jays since it opened in 1989?",
      question_type: 'text',
      category: 'Toronto Blue Jays',
      value: 300,
      alternatives: ['Exhibition Stadium', 'Rogers Centre', 'Olympic Stadium', 'Fenway Park'],
      correct: 'Rogers Centre',
      state: 'unasked',
    },
    {
      id: 'bj-4',
      question: 'Who hit the famous "Touch \'em all, Joe!" walk-off home run to win the 1993 World Series?',
      question_type: 'text',
      category: 'Toronto Blue Jays',
      value: 400,
      alternatives: ['Roberto Alomar', 'Paul Molitor', 'Joe Carter', 'John Olerud'],
      correct: 'Joe Carter',
      state: 'unasked',
    },
    {
      id: 'bj-5',
      question: 'Who was the first Blue Jays player to be inducted into the National Baseball Hall of Fame as a Jay?',
      question_type: 'text',
      category: 'Toronto Blue Jays',
      value: 500,
      alternatives: ['Roy Halladay', 'Roberto Alomar', 'Dave Stieb', 'Carlos Delgado'],
      correct: 'Roberto Alomar',
      state: 'unasked',
    },
  ],
  isChosen: false,
},
{
  name: 'Toronto Maple Leafs',
  questions: [
    {
      id: 'tml-1',
      question: 'Which of the "Original Six" NHL teams was the last one to be defeated by the Maple Leafs in a Stanley Cup Final?',
      question_type: 'text',
      category: 'Toronto Maple Leafs',
      value: 100,
      alternatives: ['Montreal Canadiens', 'Boston Bruins', 'Detroit Red Wings', 'Chicago Blackhawks'],
      correct: 'Montreal Canadiens',
      state: 'unasked',
    },
    {
      id: 'tml-2',
      question: 'Who became the captain of the Maple Leafs at the start of the 2024-25 season, succeeding John Tavares?',
      question_type: 'text',
      category: 'Toronto Maple Leafs',
      value: 200,
      alternatives: ['Auston Matthews', 'Morgan Rielly', 'William Nylander', 'Mitch Marner'],
      correct: 'Auston Matthews',
      state: 'unasked',
    },
    {
      id: 'tml-3',
      question: 'Darryl Sittler holds the NHL record for most points in a single game (10). Against which team did he achieve this feat in 1976?',
      question_type: 'text',
      category: 'Toronto Maple Leafs',
      value: 300,
      alternatives: ['Boston Bruins', 'New York Rangers', 'Philadelphia Flyers', 'Detroit Red Wings'],
      correct: 'Boston Bruins',
      state: 'unasked',
    },
    {
      id: 'tml-4',
      question: 'Before becoming the "Maple Leafs" in 1927, what was the team officially called when they won the Stanley Cup in 1922?',
      question_type: 'text',
      category: 'Toronto Maple Leafs',
      value: 400,
      alternatives: ['Toronto Arenas', 'Toronto St. Patricks', 'Toronto Blueshirts', 'Toronto Huskies'],
      correct: 'Toronto St. Patricks',
      state: 'unasked',
    },
    {
      id: 'tml-5',
      question: 'Which Maple Leafs legend was the first player in NHL history to have his jersey number (#6) officially retired?',
      question_type: 'text',
      category: 'Toronto Maple Leafs',
      value: 500,
      alternatives: ['King Clancy', 'Ace Bailey', 'Tim Horton', 'Syl Apps'],
      correct: 'Ace Bailey',
      state: 'unasked',
    },
  ],
  isChosen: false,
},
{
  name: 'Disney Princesses',
  questions: [
    {
      id: 'dp-1',
      question: 'Which Disney princess has a pet tiger named Rajah?',
      question_type: 'text',
      category: 'Disney Princesses',
      value: 100,
      alternatives: ['Belle', 'Jasmine', 'Aurora', 'Ariel'],
      correct: 'Jasmine',
      state: 'unasked',
    },
    {
      id: 'dp-2',
      question: 'What is the name of Ariel’s fish best friend in "The Little Mermaid"?',
      question_type: 'text',
      category: 'Disney Princesses',
      value: 200,
      alternatives: ['Flounder', 'Sebastian', 'Scuttle', 'Eric'],
      correct: 'Flounder',
      state: 'unasked',
    },
    {
      id: 'dp-3',
      question: 'Which Disney princess disguises herself as a man to join the army?',
      question_type: 'text',
      category: 'Disney Princesses',
      value: 300,
      alternatives: ['Pocahontas', 'Moana', 'Mulan', 'Merida'],
      correct: 'Mulan',
      state: 'unasked',
    },
    {
      id: 'dp-4',
      question: 'Which Disney princess movie features the villain Dr. Facilier?',
      question_type: 'text',
      category: 'Disney Princesses',
      value: 400,
      alternatives: ['Cinderella', 'The Princess and the Frog', 'Tangled', 'Frozen'],
      correct: 'The Princess and the Frog',
      state: 'unasked',
    },
    {
      id: 'dp-5',
      question: 'In "Sleeping Beauty," what are the names of the three good fairies?',
      question_type: 'text',
      category: 'Disney Princesses',
      value: 500,
      alternatives: ['Flora, Fauna, and Merryweather', 'Winifred, Sarah, and Mary', 'Anastasia, Drizella, and Ella', 'Rosetta, Silvermist, and Iridessa'],
      correct: 'Flora, Fauna, and Merryweather',
      state: 'unasked',
    },
  ],
  isChosen: false,
}
];